// demo-snippets/vue/Development.vue
<template>
    <Page>
        <ActionBar>
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="$navigateBack" />
            <Label text="Development Demo" />
        </ActionBar>

        <StackLayout>
            <Label text="This is the development demo..." />
        </StackLayout>
    </Page>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped></style>

// demo-snippets/svelte/Development.svelte
<style>
</style>

<page>
    <actionBar title="Development">
        <navigationButton text="Go back" on:tap={goBack} />
    </actionBar>
    <stackLayout><label text="This is the development demo..." /></stackLayout>
</page>

<script lang="typescript">
    import { goBack } from 'svelte-native';
</script>
