// demo-snippets/vue/Development.vue
<template>
    <Page>
        <ActionBar>
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="$navigateBack" />
            <Label text="Development Demo" />
        </ActionBar>

        <StackLayout>
            <Label text="This is the development demo..." />
        </StackLayout>
    </Page>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped></style>

// demo-snippets/ng/development/development.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterExtensions } from '@nativescript/angular';

@Component({
    selector: 'ns-development',
    templateUrl: './development.component.html'
})
export class DevelopmentComponent implements OnInit {
    constructor(private router: RouterExtensions) {}

    ngOnInit(): void {}

    goBack(): void {
        this.router.back();
    }
}

<ActionBar>
    <NavigationButton android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
    <Label text="Development"></Label>
</ActionBar>

<StackLayout>
    <Label text="This is the development demo..."></Label>
</StackLayout>
