// demo-snippets/svelte/Demo2.svelte
<style>
</style>

<page>
    <actionBar title="Demo 2">
        <navigationButton text="Go back" on:tap={goBack} />
    </actionBar>
    <stackLayout><label text="This is the second demo..." /></stackLayout>
</page>

<script lang="typescript">
    import { goBack } from 'svelte-native';
</script>

// demo-snippets/vue/Demo2.vue
<template>
    <Page>
        <ActionBar>
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="$navigateBack" />
            <Label text="Demo 2" />
        </ActionBar>

        <StackLayout>
            <Label text="This is the second demo..." />
        </StackLayout>
    </Page>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped></style>
