// demo-snippets/svelte/Demo1.svelte
<style>
</style>

<page>
    <actionBar title="Demo 1">
        <navigationButton text="Go back" on:tap={goBack} />
    </actionBar>
    <stackLayout>
        <label text="The version is:" />
        <versionNumber />
    </stackLayout>
</page>

<script lang="typescript">
    import { goBack } from 'svelte-native';
</script>

// demo-snippets/ng/demo1/demo1.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterExtensions } from '@nativescript/angular';

@Component({
    selector: 'ns-demo1',
    templateUrl: './demo1.component.html'
})
export class Demo1Component implements OnInit {
    constructor(private router: RouterExtensions) {}

    ngOnInit(): void {}

    goBack(): void {
        this.router.back();
    }
}

<ActionBar>
    <NavigationButton android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
    <Label text="Demo 1"></Label>
</ActionBar>

<StackLayout>
    <Label text="The version is:"></Label>
    <VersionNumber></VersionNumber>
</StackLayout>
